name: aastu_slip_managment_system

services:
  postgres:
    image: postgres:18.1
    container_name: aastu_slip_managment_system_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: aastu_sms_admin
      POSTGRES_PASSWORD: qazwsxedc
      POSTGRES_DB: aastu_slip
    ports:
      - "5432:5432"
    volumes:
      - aastu_slip_managment_system_vol:/var/lib/postgresql
    networks:
      - aastu_slip_managment_system_network

  redis:
    image: redis:alpine
    container_name: aastu_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - aastu_slip_managment_system_network

  # Temporary container to sync the database schema
  migrator:
    image: mastwal/aastu-slip-app:1.1.2
    container_name: aastu_migrator
    env_file:
      - .env.docker
    # FIXED: Added the space after "command:"
    command: ["npx", "prisma", "db", "push"]
    depends_on:
      - postgres
    networks:
      - aastu_slip_managment_system_network
    restart: "no" # Runs once and exits

  nextjs_app:
    image: mastwal/aastu-slip-app:1.1.2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aastu-slip-managment
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - aastu_slip_managment_system_network
    depends_on:
      - postgres
      - redis
      - migrator

  worker:
    image: mastwal/aastu-slip-app:1.1.2
    container_name: aastu_worker
    restart: unless-stopped
    env_file:
      - .env.docker
    # FIXED: Added the space after "command:"
    command: ["node", "dist/worker.js"]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - aastu_slip_managment_system_network
    depends_on:
      - postgres
      - redis
      - migrator

volumes:
  aastu_slip_managment_system_vol:

networks:
  aastu_slip_managment_system_network:
    driver: bridge
